name: NASA PROJECT CI
# we can control when the workflow will run using this " on: " property -> we can define differernt triggers that will cause workflows to run
on:
# on what effect should run and on which branches ->
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # what jobs we need to run based on above conditions
  # things that we put inside steps are the different resuable scripts 
  # actions/checkout is built in action 
  # run command is usefull to run our own commands
  # - name: is used to name our step
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 16
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build --prefix client


